apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-app.nextopsvideos.com
    http:
      paths:
      - path: /blue
        pathType: Prefix
        backend:
          service:
            name: my-app-blue
            port:
              name: http
      - path: /green
        pathType: Prefix
        backend:
          service:
            name: my-app-green
            port:
              name: http
      - path: /canary
        pathType: Prefix
        backend:
          service:
            name: my-app-canary
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-canary-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "user-agent"
    nginx.ingress.kubernetes.io/canary-by-header-value: "canary"
    nginx.ingress.kubernetes.io/canary-by-header-mode: "exact"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  rules:
  - host: canary.my-app.nextopsvideos.com
    http:
      paths:
      - path: /canary
        pathType: Prefix
        backend:
          service:
            name: my-app-canary
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-blue-green-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "user-agent"
    nginx.ingress.kubernetes.io/canary-by-header-value: "canary"
    nginx.ingress.kubernetes.io/canary-by-header-mode: "exact"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  rules:
  - host: my-app.nextopsvideos.com
    http:
      paths:
      - path: /blue
        pathType: Prefix
        backend:
          service:
            name: my-app-blue
            port:
              name: http
      - path: /green
        pathType: Prefix
        backend:
          service:
            name: my-app-green
            port:
              name: http
